-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Май 29 2018 г., 18:39
-- Версия сервера: 5.7.20
-- Версия PHP: 5.6.32

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `colevents.com.ua`
--
CREATE DATABASE IF NOT EXISTS `colevents.com.ua` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `colevents.com.ua`;

-- --------------------------------------------------------

--
-- Структура таблицы `blog`
--

CREATE TABLE `blog` (
  `id` int(11) NOT NULL,
  `user_post` varchar(100) NOT NULL,
  `date_post` date NOT NULL,
  `image_post` text NOT NULL,
  `small_text_post` text NOT NULL,
  `big_text_post` text NOT NULL,
  `title_post` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `blog`
--

INSERT INTO `blog` (`id`, `user_post`, `date_post`, `image_post`, `small_text_post`, `big_text_post`, `title_post`) VALUES
(1, 'Admin', '2018-05-24', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Developer'),
(2, 'Admin', '2018-05-22', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Web design'),
(3, 'Admin', '2018-05-09', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'VirusTOtal'),
(4, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post'),
(5, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 2'),
(6, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 3'),
(7, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 4'),
(8, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 5'),
(9, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 6'),
(10, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 7'),
(11, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 8'),
(12, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 9'),
(13, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 10'),
(14, 'Admin', '2018-05-17', '../img/news_prev.jpg', '              <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', '  <p>Equally, the strengthening and development of the structure allows carrying out important tasks in the development of systems of mass participation. Diverse and rich experience a new model of organizational activity makes it possible to assess the importance of forms of development. On the other hand, the constant information and propaganda support of our activities allows us to carry out important tasks for the development of appropriate conditions for activation. Everyday practice shows that the further development of various forms of activity allows performing important tasks in the development of directions for progressive development. We should not, however, forget that the framework and place of training of personnel contributes to the preparation and implementation of forms of development.</p>\r\n              <p>The task of the organization, especially the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>\r\n              <p>The task of the organization, <mark>especially</mark> the framework and place of training of personnel, is an interesting experiment to verify the systems of mass participation. Equally, the strengthening and development of the structure requires the definition and refinement of the directions of progressive development.</p>', 'Vot takoi post 11');

-- --------------------------------------------------------

--
-- Структура таблицы `comments_blog`
--

CREATE TABLE `comments_blog` (
  `id` int(11) NOT NULL,
  `id_blog` int(11) NOT NULL,
  `author` varchar(50) NOT NULL,
  `text` text NOT NULL,
  `date` datetime NOT NULL,
  `comments_user_type` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `comments_blog`
--

INSERT INTO `comments_blog` (`id`, `id_blog`, `author`, `text`, `date`, `comments_user_type`) VALUES
(1, 3, 'Xelinel32', 'drfetrvtertv', '2018-05-28 16:36:39', 'Юзер'),
(2, 3, 'Xelinel32', 'werfwefwefr', '2018-05-28 16:40:23', 'Юзер'),
(3, 13, 'Xelinel32', 'Добре тут у вас)', '2018-05-28 16:49:17', 'Юзер'),
(4, 3, 'Artemiy', 'И админ тут', '2018-05-28 16:59:44', 'Адміністрація'),
(5, 3, 'Xelinel32', 'hello world', '2018-05-29 12:58:31', 'Юзер'),
(6, 4, 'Artemiy', 'а я админ', '2018-05-29 12:59:10', 'Адміністрація'),
(7, 4, 'Xelinel32', 'norm', '2018-05-29 13:11:01', 'Юзер'),
(8, 3, 'Xelinel32', 'ya dayn', '2018-05-29 14:40:28', 'Юзер');

-- --------------------------------------------------------

--
-- Структура таблицы `multi_login`
--

CREATE TABLE `multi_login` (
  `id` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `user_type` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `pib` varchar(100) NOT NULL,
  `image` varchar(255) NOT NULL,
  `phone_number` varchar(20) NOT NULL,
  `adress` varchar(200) NOT NULL,
  `sex` varchar(20) NOT NULL,
  `age` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `multi_login`
--

INSERT INTO `multi_login` (`id`, `username`, `email`, `user_type`, `password`, `pib`, `image`, `phone_number`, `adress`, `sex`, `age`) VALUES
(1, 'Artemiy', 'bombopedroua@gmail.com', 'Адміністрація', '123qaz', 'Artem Sedlyar Vitalievich', '../img/admin.png', '380935039351', 'Шевченка 53в, Чернігів , Україна', 'Чоловіча', '18'),
(2, 'Xelinel32', 'xelinel32@outlook.com', 'Юзер', '123qaz', 'Artem Sedlyar', '../img/user.png', '380935039351', 'Шевченка 53в, Чернігів , Україна', 'Чоловіча', '19'),
(3, 'Vladik228', 'bombopedroua@gmail.com', 'Юзер', '123qaz', 'Vladik Vladikovich', '../img/user.png', '234234234', 'erwerwrc', 'male', '20');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `blog`
--
ALTER TABLE `blog`
  ADD PRIMARY KEY (`id`);

--
-- Индексы таблицы `comments_blog`
--
ALTER TABLE `comments_blog`
  ADD PRIMARY KEY (`id`),
  ADD KEY `id_blog` (`id_blog`);

--
-- Индексы таблицы `multi_login`
--
ALTER TABLE `multi_login`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `blog`
--
ALTER TABLE `blog`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;

--
-- AUTO_INCREMENT для таблицы `comments_blog`
--
ALTER TABLE `comments_blog`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT для таблицы `multi_login`
--
ALTER TABLE `multi_login`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- Ограничения внешнего ключа сохраненных таблиц
--

--
-- Ограничения внешнего ключа таблицы `comments_blog`
--
ALTER TABLE `comments_blog`
  ADD CONSTRAINT `comments_blog_ibfk_1` FOREIGN KEY (`id_blog`) REFERENCES `blog` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
